[workspace]
members = ["cargo:."]

[dist]
cargo-dist-version = "0.31.0"
allow-dirty = ["ci"]
ci = "github"
installers = ["homebrew"]
tap = "mi2428/homebrew-clockping"
publish-jobs = ["homebrew"]
targets = [
  "aarch64-apple-darwin",
  "aarch64-unknown-linux-gnu",
  "x86_64-apple-darwin",
  "x86_64-unknown-linux-gnu",
]
hosting = "github"
github-build-setup = "../dist-build-setup.yml"
